/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package gui;

import classes.*;
import structures.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import structures.NodeFS;

public class MainFrame extends javax.swing.JFrame {

    // --- INSTANCIAS DEL NÚCLEO (Backend) ---
    private Disk disco = new Disk(100); 
    private TreeFS.ArbolSistemaArchivos arbolLogic = new TreeFS().new ArbolSistemaArchivos(disco);
    private newCustomQueue colaListos = new newCustomQueue();
    private newCustomQueue colaBloqueados = new newCustomQueue();
    private newCustomQueue colaES = new newCustomQueue();
    private ThreadScheduler scheduler;

    // --- VISUALIZACIÓN (Frontend) ---
    private JLabel[] bloquesVisuales = new JLabel[100];
    private ButtonGroup grupoModo = new ButtonGroup();

    public MainFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        // Configurar RadioButtons
        grupoModo.add(rbAdmin);
        grupoModo.add(rbUsuario);
        rbAdmin.setSelected(true);
        
        inicializarDiscoGrafico();
        actualizarJTree();

        // Iniciar el motor (Scheduler)
        scheduler = new ThreadScheduler(colaListos, colaBloqueados, colaES, arbolLogic, txtJournal);
        scheduler.start();

        // Timer para refrescar la interfaz cada 500ms
        new javax.swing.Timer(500, e -> {
            actualizarPantalla();
            actualizarPermisos();
        }).start();
    }







    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rbAdmin = new javax.swing.JRadioButton();
        rbUsuario = new javax.swing.JRadioButton();
        comboAlgoritmo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnLeer = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnPruebaEstras = new javax.swing.JButton();
        btnCargarCSV = new javax.swing.JButton();
        btnGuardarCSV = new javax.swing.JButton();
        btnCrearArchivo = new javax.swing.JButton();
        btnCrearCarpeta = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        treeFiles = new javax.swing.JTree();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        panelBloquesDisco = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableProcesos = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableFAT = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtJournal = new javax.swing.JTextArea();
        jPanel10 = new javax.swing.JPanel();
        lblTotalBloques = new javax.swing.JLabel();
        lblUsados = new javax.swing.JLabel();
        lblLibres = new javax.swing.JLabel();
        lblPosCabezal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(168, 255, 255));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Simulador de Sistema de Archivos Concurrente");

        jPanel2.setForeground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Modo:");

        rbAdmin.setText("Administrador");
        rbAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAdminActionPerformed(evt);
            }
        });

        rbUsuario.setText("Usuario");
        rbUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbUsuario)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(rbAdmin)
                    .addComponent(rbUsuario))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        comboAlgoritmo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FIFO", "SSTF", "SCAN", "C-SCAN" }));
        comboAlgoritmo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAlgoritmoActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 118, 118));
        jButton1.setText("SIMULAR FALLO");

        btnLeer.setText("Leer");

        btnActualizar.setText("Actualizar");

        btnPruebaEstras.setText("Crear 10 Procesos");
        btnPruebaEstras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPruebaEstrasActionPerformed(evt);
            }
        });

        btnCargarCSV.setText("Cargar CSV");

        btnGuardarCSV.setText("Guardar Historial");

        btnCrearArchivo.setText("Crear Archivo");

        btnCrearCarpeta.setText("Crear Directorio");

        btnEliminar.setText("Eliminar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnLeer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPruebaEstras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCargarCSV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGuardarCSV))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnCrearArchivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCrearCarpeta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminar)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLeer)
                    .addComponent(btnActualizar)
                    .addComponent(btnPruebaEstras)
                    .addComponent(btnCargarCSV)
                    .addComponent(btnGuardarCSV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearArchivo)
                    .addComponent(btnCrearCarpeta)
                    .addComponent(btnEliminar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setViewportView(treeFiles);

        jLabel6.setText("...");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel6)
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelBloquesDiscoLayout = new javax.swing.GroupLayout(panelBloquesDisco);
        panelBloquesDisco.setLayout(panelBloquesDiscoLayout);
        panelBloquesDiscoLayout.setHorizontalGroup(
            panelBloquesDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 571, Short.MAX_VALUE)
        );
        panelBloquesDiscoLayout.setVerticalGroup(
            panelBloquesDiscoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 353, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBloquesDisco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBloquesDisco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Visualización del Disco", jPanel6);

        tableProcesos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Operación (CRUD)", "Estado", "Bloque Actual"
            }
        ));
        jScrollPane2.setViewportView(tableProcesos);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Gestor de Procesos", jPanel7);

        tableFAT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre Archivo", "Bloques Usados", "Índice Inicio", "Locks"
            }
        ));
        jScrollPane3.setViewportView(tableFAT);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Tabla de Asignación", jPanel8);

        txtJournal.setColumns(20);
        txtJournal.setRows(5);
        jScrollPane4.setViewportView(txtJournal);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Bitácora y Journaling", jPanel9);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblTotalBloques.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalBloques.setText("Total Bloques: 100");

        lblUsados.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUsados.setText("Usados: X");

        lblLibres.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblLibres.setText("Libre: Y");

        lblPosCabezal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPosCabezal.setText("Cabeza en: Z");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(lblTotalBloques)
                .addGap(18, 18, 18)
                .addComponent(lblUsados)
                .addGap(18, 18, 18)
                .addComponent(lblLibres)
                .addGap(18, 18, 18)
                .addComponent(lblPosCabezal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalBloques)
                    .addComponent(lblUsados)
                    .addComponent(lblPosCabezal)
                    .addComponent(lblLibres))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboAlgoritmo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboAlgoritmo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboAlgoritmoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAlgoritmoActionPerformed
            String seleccionado = comboAlgoritmo.getSelectedItem().toString();
            scheduler.setPoliticaActiva(seleccionado);
            txtJournal.append(">>> SISTEMA: Cambiando algoritmo a " + seleccionado + "\n");
    }//GEN-LAST:event_comboAlgoritmoActionPerformed

    private void btnPruebaEstrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPruebaEstrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPruebaEstrasActionPerformed

    private void rbAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAdminActionPerformed
        actualizarPermisos();
    }//GEN-LAST:event_rbAdminActionPerformed

    private void rbUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbUsuarioActionPerformed
        actualizarPermisos();
    }//GEN-LAST:event_rbUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private void btnPruebaEstrasActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // Datos del Caso de Prueba del PDF (pág. 6)
        // Nota: cambié 180, 119 y 123 por números menores a 100 para que coincidan con tu disco actual
            int[] peticiones = {95, 80, 34, 19, 11, 23, 62, 64};
            txtJournal.append(">>> CARGANDO CASO DE PRUEBA PDF\n");

            for (int i = 0; i < peticiones.length; i++) {
                int bloqueDestino = peticiones[i];
                // Creamos procesos de LECTURA para probar los movimientos del cabezal
                PCB proceso = new PCB("LEER", null, bloqueDestino, "Prueba_" + bloqueDestino, 1);
                colaListos.encolar(proceso);
                txtJournal.append("[PENDIENTE] Proceso " + proceso.getId() + " solicita bloque " + bloqueDestino + "\n");
            }
            JOptionPane.showMessageDialog(this, "8 Procesos cargados según el caso de prueba del PDF.");
        }

        JOptionPane.showMessageDialog(this, "8 Procesos cargados según el PDF.\nEl cabezal empezará a moverse usando el algoritmo: " + comboAlgoritmo.getSelectedItem());
    }
    private void btnCrearArchivoActionPerformed(java.awt.event.ActionEvent evt) {                                               
        String nombre = JOptionPane.showInputDialog(this, "Nombre del archivo:");
        String tamStr = JOptionPane.showInputDialog(this, "Tamaño (bloques):");

        if (nombre != null && tamStr != null) {
            try {
                int tamano = Integer.parseInt(tamStr);
                // Registro en Journal (Requisito 8)
                txtJournal.append("[PENDIENTE] CREAR ARCHIVO: " + nombre + "\n");

                // Buscamos un bloque destino aproximado (el primero libre)
                int destino = buscarPrimerBloqueLibre();

                // Creamos el PCB (ticket) y lo mandamos a la cola de listos
                PCB solicitud = new PCB("CREAR", null, destino, nombre, tamano);
                colaListos.encolar(solicitud);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Error: El tamaño debe ser un número.");
            }
        }                                             

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> {
            new MainFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCargarCSV;
    private javax.swing.JButton btnCrearArchivo;
    private javax.swing.JButton btnCrearCarpeta;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardarCSV;
    private javax.swing.JButton btnLeer;
    private javax.swing.JButton btnPruebaEstras;
    private javax.swing.JComboBox<String> comboAlgoritmo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblLibres;
    private javax.swing.JLabel lblPosCabezal;
    private javax.swing.JLabel lblTotalBloques;
    private javax.swing.JLabel lblUsados;
    private javax.swing.JPanel panelBloquesDisco;
    private javax.swing.JRadioButton rbAdmin;
    private javax.swing.JRadioButton rbUsuario;
    private javax.swing.JTable tableFAT;
    private javax.swing.JTable tableProcesos;
    private javax.swing.JTree treeFiles;
    private javax.swing.JTextArea txtJournal;
    // End of variables declaration//GEN-END:variables

    
    // --- MÉTODOS DE APOYO VISUAL (MVC: La vista se actualiza consultando al motor) ---

    private void inicializarDiscoGrafico() {
        panelBloquesDisco.setLayout(new GridLayout(10, 10, 2, 2));
        panelBloquesDisco.removeAll();
        for (int i = 0; i < 100; i++) {
            bloquesVisuales[i] = new JLabel(String.valueOf(i), SwingConstants.CENTER);
            bloquesVisuales[i].setOpaque(true);
            bloquesVisuales[i].setBackground(Color.LIGHT_GRAY);
            bloquesVisuales[i].setBorder(BorderFactory.createLineBorder(Color.BLACK));
            panelBloquesDisco.add(bloquesVisuales[i]);
        }
        panelBloquesDisco.revalidate();
        panelBloquesDisco.repaint();
    }

    public void actualizarPantalla() {
        // 1. Pintar ocupación de bloques
        Block[] bloquesLogicos = disco.getBloques();
        int usados = 0;
        for (int i = 0; i < 100; i++) {
            if (bloquesLogicos[i].isOcupado()) {
                bloquesVisuales[i].setBackground(Color.CYAN);
                usados++;
            } else {
                bloquesVisuales[i].setBackground(Color.LIGHT_GRAY);
            }
            // Mostrar posición del cabezal
            if (i == scheduler.getPosicionCabezal()) {
                bloquesVisuales[i].setBorder(BorderFactory.createLineBorder(Color.RED, 3));
            } else {
                bloquesVisuales[i].setBorder(BorderFactory.createLineBorder(Color.BLACK));
            }
        }
        
        // 2. Actualizar Labels
        lblUsados.setText("Usados: " + usados);
        lblLibres.setText("Libre: " + (100 - usados));
        lblPosCabezal.setText("Cabeza: " + scheduler.getPosicionCabezal());
        
        // 3. CPU Visual
        PCB p = scheduler.getProcesoActual();
        jLabel6.setText(p != null ? "ID: " + p.getId() + " [" + p.getOperacion() + "]" : "ID: --- (IDLE)");
        
        // 4. Actualizar Tablas y Árbol
        actualizarTablaProcesos();
        actualizarTablaFAT();
        actualizarJTree();
    }

    private void actualizarTablaProcesos() {
        DefaultTableModel model = (DefaultTableModel) tableProcesos.getModel();
        model.setRowCount(0); // Limpiar tabla

        // 1. Mostrar el proceso que está usando el disco actualmente
        PCB actual = scheduler.getProcesoActual();
        if (actual != null) {
            model.addRow(new Object[]{actual.getId(), actual.getOperacion(), "EJECUTANDO", actual.getBloqueDestino()});
        }

        // 2. Mostrar los procesos que están esperando en la Cola de Listos
        // Como no podemos usar iteradores de Java, recorremos la cola manualmente
        int size = colaListos.getSize();
        for (int i = 0; i < size; i++) {
            PCB p = colaListos.get(i); // Usando el método get(i) que creamos en la cola
            if (p != null) {
                model.addRow(new Object[]{p.getId(), p.getOperacion(), "LISTO", p.getBloqueDestino()});
            }
        }
    }

    private void actualizarTablaFAT() {
        DefaultTableModel model = (DefaultTableModel) tableFAT.getModel();
        model.setRowCount(0);
        Block[] bloques = disco.getBloques();
        for (Block b : bloques) {
            if (b.isOcupado() && b.getSiguienteBloque() == -1) { 
                model.addRow(new Object[]{b.getPropietario(), "Enlazados", b.getIndice(), "None"});
            }
        }
    }

    public void actualizarJTree() {
        NodeFS raizLogica = arbolLogic.getRaiz();
        DefaultMutableTreeNode raizVisual = new DefaultMutableTreeNode(raizLogica.getNombre());
        llenarNodosJTree(raizLogica, raizVisual);
        treeFiles.setModel(new DefaultTreeModel(raizVisual));
    }

    private void llenarNodosJTree(NodeFS nodoLogico, DefaultMutableTreeNode nodoVisual) {
        NodeFS hijoActual = nodoLogico.getPrimerHijo();
        while (hijoActual != null) {
            DefaultMutableTreeNode nuevoNodoVisual = new DefaultMutableTreeNode(hijoActual.getNombre());
            nodoVisual.add(nuevoNodoVisual);
            if (hijoActual.isEsDirectorio()) {
                llenarNodosJTree(hijoActual, nuevoNodoVisual);
            }
            hijoActual = hijoActual.getSiguienteHermano();
        }
    }

    private void actualizarPermisos() {
        boolean isAdmin = rbAdmin.isSelected();
        btnCrearArchivo.setEnabled(isAdmin);
        btnCrearCarpeta.setEnabled(isAdmin);
        btnEliminar.setEnabled(isAdmin);
        comboAlgoritmo.setEnabled(isAdmin);
    }
    
    
}

